generator: admingenerator.generator.doctrine_odm
params:
  model: Admingenerator\DoctrineODMDemoBundle\Document\Movie
  namespace_prefix: Admingenerator
  bundle_name: DoctrineODMDemoBundle
  fields:
    is_published:
      help: If you want to see this content on you website
    actors:
      filterOn: actors.id
    producer:
      label: Producer name
      sort_on: producer.name
      getter: producer.name
      addFormOptions:
        property: name
    release_date:
      formType: birthday
      addFormOptions:
        format: "Y-m-d"
        years:
          .range:
            from: <?php echo date("Y"); ?>

            to: 1950
            step: 1


builders:
  list:
    params:
      scopes:
        group_1: 
          All: ~
          Published: 
            default: true
            filters: 
              is_published: true
          "Not Published": 
            filters: 
              is_published: false
        group_2:
          "With actors":
             filters: [ withActors ]
          "Without actos":
             filters: [ withoutActors ]
      title: Here is a beautifull title no  ???
      display: [ id, title, is_published, producer, release_date ]
      max_per_page: 3
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: 
          confirm: Are you sure to delete {{ Movie.title }} ?
  filters:
    params:
      fields:
        release_date:
          formType: date_range
      display: [ title, is_published, actors, producer, release_date]

  new:
    params:
      title: You're creating a new movie
      display: [ title, is_published, actors, producer, release_date ]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the movie "{{ Movie.title }}"
      display:
        "NONE": [ title, release_date ]
        "Other informations": [[ is_published ], [ producer, actors ]]
      actions:
        list: ~
  delete: ~
