generator: admingenerator.generator.propel
params:
  model: Admingenerator\PropelDemoBundle\Model\Movie
  namespace_prefix: Admingenerator
  bundle_name: PropelDemoBundle
  fields:
    ActorRelatedByActorId:
      label: Actors
      filterOn: ActorHasMovieRelatedById.ActorId
    is_published:
      help: If you want to see this content on you website
    producer:
      label: Producer name
      sort_on: Producer.Name
      getter: Producer
      addFormOptions:
        property: Name
    release_date:
      formType: birthday
      addFormOptions:
        format: "Y-m-d"
        years:
          .range:
            from: <?php echo date("Y"); ?>

            to: 1950
            step: 1

builders:
  list:
    params:
      scopes:
        group_1: 
          All: ~
          Published: 
            default: true
            filters: 
              filterByIsPublished: true
          "Not Published": 
            filters: 
              filterByIsPublished: false
        group_2:
          "With actors":
             filters: [ withActors ]
          "Without actos":
             filters: [ withoutActors ]
         
      title: Here is a beautifull title no  ???
      display: [ id, title, is_published, release_date, producer ]
      max_per_page: 3
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: 
          confirm: Are you sure to delete {{ Movie.title }} ?
  filters:
    params:
      fields:
        release_date:
          formType: date_range
      display: [ title, is_published, release_date, producer, ActorHasMovie ]
  new:
    params:
      title: You're creating a new movie
      display: [ title, is_published, release_date, producer, ActorHasMovie ]
      actions:
        list: ~
  edit:
    params:
      title: You're editing the movie "{{ Movie.title }}"
      fields:
        actors:
          formType: collection
          dbType: collection
          addFormOptions:
            type: \Admingenerator\PropelDemoBundle\Form\Type\ActorType
      display:
        "NONE": [ title, release_date ]
        "Other informations": [[ is_published ], [producer, actors ]]
      actions:
        list: ~
  delete: ~
